### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by mvhirsch** [rezzza/alice-extension#46]
Hey there!

I really like your library, but I'm afraid, I can't use it in my project since it misses a license.
Could you please provide one?

Thank you very much!

**Comment by tyx** [comment]
Hello !

Good catch. As mentionned inside the composer.json https://github.com/rezzza/alice-extension/blob/master/composer.json#L6 => MIT

I will add the LICENCE file

**Comment by mvhirsch** [comment]
Wow, that was fast! Thank you!

**Comment by tyx** [comment]
That was easy thanks to github ;)
